[build]
cmd = "go build -o ./tmp/main ./cmd/go-short-sql"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = true

[misc]
clean_on_exit = true

[screen]
keep_scroll = true
